name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91a8c3a6ad41ec1df36fe56c4a76f004af57c92192a82072b07bde74ddec4089"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
