name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aab9adee14ab4b76e1d641913018735f4689509bfde519afc5a9317c5275b721"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
