name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "846a260af74e9cad9083eaec55e5881d43ac2bff5fde1cfdf172f5bb0f294ac7"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
