name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a673004e13b1d10aa0434493debb559b85a9fc4f6866aab36ff09bb00188b979"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
