name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0f93328564987693de4541d89d1cf8a564bc441c58858e2c66117c403e81185"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
