name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "158d6749ba77ad4a49947dcdf8934589c1cac79b11938e3235c233220dbb5166"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
