name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9489f9ad5886d829e2d547ab499158d751d989d7eda496983b9478b7ad36eaa1"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
