name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11aefdb5e8c61fe52b9b6b1d23114fa5b92d1d9e9be531676e7fb96cc3077d10"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
