name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71981710e7fc9e960b7415ff5976913894628368f7139f07d9aa998bad49250f"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
