name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b7a38d0b2dbb503ffb0cd57f93e2ced82e5bb9fe7ad90ee86e1d583a51d1d07"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
