name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "653eeece5550585a8ade7740858e0089838e9299f0e0ede3a083a518a7434813"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
