name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf163a431434dcfea5ac32dce18546e7ba41f5e80e200c205e8692cc3404cb10"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
