name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9abcae144511a4cbb74180750af9463b8970d1e208c945adb3ef8de6e468e2ec"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
