name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bde73dd91e174e008905cd66095df280db7ac1f9e993270bdc8a3fc670f62ba"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
