name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e548790cd6f230c868b6b80f3314bdff34168e72ec041e4da80162ecb20971a9"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
