name = "A Folk of A Thaumaturge"
author = "Siria Kurume"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "422a53ae8ac1403aa74b90027584abdb74c51a7ad536f87e68c45c6281d112f7"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
